import type { Locale } from "./contracts";

const en = {
  loading: "Checking Restaurant access…", offlineTitle: "No internet connection.", offlineMessage: "Live orders cannot update while offline. Reconnect before responding to an order.", unavailable: "Restaurant services are unavailable. Try again.",
  invalidMenu: "Check each option group: add enough named options for its maximum, and use valid non-negative prices.", invalidMedia: "Use a JPEG, PNG, or WebP image up to 5 MB.", mediaUploadFailed: "The image could not be uploaded. Try again.", menuSaveFailed: "The menu item could not be saved. Try again.", saving: "Saving…", retry: "Retry",
  signIn: "Sign in", signingIn: "Signing in…", email: "Email", password: "Password", showPassword: "Show password", hidePassword: "Hide password", invalid: "Incorrect email or password.", forgotPassword: "Forgot password?", backToLogin: "Back to sign in", resetPassword: "Reset password", resetIntro: "Enter your account email. If an account is eligible, Firebase will send reset instructions.", resetSent: "If an eligible account exists for this email, password reset instructions have been sent.", resetFailed: "The request could not be completed. Check your connection and try again.",
  pending: "Your Restaurant account is waiting for approval.", pendingTitle: "Approval pending", pendingDetail: "You can sign in after an administrator approves this Restaurant account.", suspended: "Restaurant access is suspended. Contact support.", suspendedTitle: "Access suspended", revoked: "Your Restaurant access was revoked. Sign in with an authorized account.", wrongRole: "This account cannot use the Restaurant portal.", sessionExpired: "Your session ended. Sign in again.", accessFailed: "Restaurant access could not be verified.",
  dashboard: "Dashboard", orders: "Live orders", history: "History", menu: "Menu", restaurant: "Restaurant", reviews: "Reviews", settings: "Alerts", security: "Security", earnings: "Earnings", more: "More", logout: "Sign out", owner: "Owner", manager: "Manager", account: "Restaurant account",
  accepting: "Accepting orders", connection: "Live updates", enablePush: "Enable notifications", testPush: "Test notification", pushRegistering: "Connecting notifications…", pushIosInstall: "On iPhone or iPad, tap Share → Add to Home Screen. Then open Hungrie Restaurant from its Home Screen icon and enable notifications there.", pushPermissionOnly: "Browser permission is granted, but alerts are not connected.", pushDisabled: "Notifications are not enabled.", pushTokenFailed: "The browser could not create a notification token. Refresh and try again.", pushRegistrationFailed: "The notification token could not be registered. Refresh and try again.", pushDisableFailed: "Notifications could not be disabled. Try again.", pushDenied: "Notifications are unavailable on this browser or device. Keep the qualified desktop order screen staffed.",
  save: "Save", refresh: "Refresh", noRows: "No records", open: "Open", activate: "Available", deactivate: "Unavailable", language: "Language", invite: "Accept Restaurant invitation", inviteIntro: "Create an account or sign in to accept this Restaurant invitation.", inviteUnavailable: "Invitation is unavailable or expired. Ask an Admin for a new link.", create: "Create account", existingAccount: "Existing account", newAccount: "New account", verify: "Verify your email, then reopen this invitation link and choose Existing account to accept it.", confirm: "Confirm", reason: "Reason", note: "Internal note", changed: "This order changed. Refresh and retry.",
  workspace: "Workspace", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", skipToContent: "Skip to content", secondaryNavigation: "Restaurant tools", accountAndLanguage: "Account and language",
  runtimeStatus: { offline: "Offline", connecting: "Connecting live updates", connected: "Live updates connected", stale: "Dashboard status may be outdated" },
};

const tr: typeof en = {
  loading: "Restoran erişimi kontrol ediliyor…", offlineTitle: "İnternet bağlantısı yok.", offlineMessage: "Çevrimdışıyken canlı siparişler güncellenemez. Bir siparişe yanıt vermeden önce yeniden bağlanın.", unavailable: "Restoran hizmetleri kullanılamıyor. Tekrar deneyin.",
  invalidMenu: "Her seçenek grubunu kontrol edin: maksimum seçim sayısı kadar adlandırılmış seçenek ekleyin ve geçerli, negatif olmayan fiyatlar kullanın.", invalidMedia: "En fazla 5 MB boyutunda JPEG, PNG veya WebP görsel kullanın.", mediaUploadFailed: "Görsel yüklenemedi. Tekrar deneyin.", menuSaveFailed: "Menü ürünü kaydedilemedi. Tekrar deneyin.", saving: "Kaydediliyor…", retry: "Tekrar dene",
  signIn: "Giriş yap", signingIn: "Giriş yapılıyor…", email: "E-posta", password: "Şifre", showPassword: "Şifreyi göster", hidePassword: "Şifreyi gizle", invalid: "E-posta veya şifre hatalı.", forgotPassword: "Şifrenizi mi unuttunuz?", backToLogin: "Girişe dön", resetPassword: "Şifreyi yenile", resetIntro: "Hesap e-postanızı girin. Uygun bir hesap varsa Firebase yenileme talimatlarını gönderir.", resetSent: "Bu e-posta için uygun bir hesap varsa şifre yenileme talimatları gönderildi.", resetFailed: "İstek tamamlanamadı. Bağlantınızı kontrol edip tekrar deneyin.",
  pending: "Restoran hesabınız onay bekliyor.", pendingTitle: "Onay bekleniyor", pendingDetail: "Bir yönetici bu Restoran hesabını onayladıktan sonra giriş yapabilirsiniz.", suspended: "Restoran erişimi askıya alındı. Destekle iletişime geçin.", suspendedTitle: "Erişim askıya alındı", revoked: "Restoran erişiminiz kaldırıldı. Yetkili bir hesapla giriş yapın.", wrongRole: "Bu hesap Restoran portalını kullanamaz.", sessionExpired: "Oturumunuz sona erdi. Tekrar giriş yapın.", accessFailed: "Restoran erişimi doğrulanamadı.",
  dashboard: "Genel Bakış", orders: "Canlı siparişler", history: "Geçmiş", menu: "Menü", restaurant: "Restoran", reviews: "Değerlendirmeler", settings: "Uyarılar", security: "Güvenlik", earnings: "Kazançlar", more: "Daha Fazla", logout: "Çıkış yap", owner: "Sahip", manager: "Yönetici", account: "Restoran hesabı",
  accepting: "Sipariş alımı", connection: "Canlı güncellemeler", enablePush: "Bildirimleri etkinleştir", testPush: "Bildirimi test et", pushRegistering: "Bildirimler bağlanıyor…", pushIosInstall: "iPhone veya iPad'de Paylaş → Ana Ekrana Ekle'ye dokunun. Ardından Hungrie Restaurant'ı Ana Ekran simgesinden açıp bildirimleri orada etkinleştirin.", pushPermissionOnly: "Tarayıcı izni verildi ancak uyarılar bağlı değil.", pushDisabled: "Bildirimler etkin değil.", pushTokenFailed: "Tarayıcı bildirim anahtarı oluşturamadı. Sayfayı yenileyip tekrar deneyin.", pushRegistrationFailed: "Bildirim anahtarı kaydedilemedi. Sayfayı yenileyip tekrar deneyin.", pushDisableFailed: "Bildirimler devre dışı bırakılamadı. Tekrar deneyin.", pushDenied: "Bildirimler bu tarayıcıda veya cihazda kullanılamıyor. Onaylı masaüstü sipariş ekranını personelli tutun.",
  save: "Kaydet", refresh: "Yenile", noRows: "Kayıt yok", open: "Aç", activate: "Satışta", deactivate: "Satış dışı", language: "Dil", invite: "Restoran davetini kabul et", inviteIntro: "Bu Restoran davetini kabul etmek için hesap oluşturun veya giriş yapın.", inviteUnavailable: "Davet kullanılamıyor veya süresi dolmuş. Yöneticiden yeni bağlantı isteyin.", create: "Hesap oluştur", existingAccount: "Mevcut hesap", newAccount: "Yeni hesap", verify: "E-postanızı doğrulayın, ardından bu davet bağlantısını yeniden açıp Mevcut hesap'ı seçin.", confirm: "Onayla", reason: "Neden", note: "Dahili not", changed: "Bu sipariş değişti. Yenileyip tekrar deneyin.",
  workspace: "Çalışma Alanı", primaryNavigation: "Ana navigasyon", mobileNavigation: "Mobil navigasyon", skipToContent: "İçeriğe geç", secondaryNavigation: "Restoran araçları", accountAndLanguage: "Hesap ve dil",
  runtimeStatus: { offline: "Çevrimdışı", connecting: "Canlı güncellemeler bağlanıyor", connected: "Canlı güncellemeler bağlı", stale: "Panel durumu güncel olmayabilir" },
};

const copy = { en, tr };
export const translations = (locale: Locale) => copy[locale];
