import { Check, ChevronDown, ChevronUp, Pencil, Plus, RefreshCw, Utensils } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Shell } from "./Shell";
import { Button } from "./components/Button";
import { Dialog } from "./components/Dialog";
import { FormField, TextAreaField } from "./components/FormField";
import { PageHeader } from "./components/PageHeader";
import { type MenuCategory, type MenuItem, type MenuSnapshot } from "./managementContract";
import { completeManagementIntent, stableManagementOperationId } from "./managementModel";
import { restaurantManagementRepository } from "./managementRepository";
import { draftFromItem, type MenuItemDraft } from "./menuModel";
import { MenuItemDialog } from "./MenuItemDialog";
import { useDirtyGuard } from "./useDirtyGuard";
import { useLocale } from "./providers";

const money = (value: number, locale: string) => new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-GB", { style: "currency", currency: "TRY" }).format(value / 100);
const EMPTY: MenuSnapshot = { restaurantId: "", categories: [], items: [], ingredients: [], groups: [], options: [] };

export function MenuPage() {
  const { locale, t } = useLocale();
  const [data, setData] = useState<MenuSnapshot>(EMPTY), [selectedCategory, setSelectedCategory] = useState(""), [selectedItems, setSelectedItems] = useState<string[]>([]);
  const [loading, setLoading] = useState(true), [stale, setStale] = useState(false), [error, setError] = useState(""), [busy, setBusy] = useState(false), [retryAction, setRetryAction] = useState<null | (() => void)>(null);
  const [categoryEdit, setCategoryEdit] = useState<MenuCategory | "new" | null>(null), [categoryName, setCategoryName] = useState(""), [categoryDescription, setCategoryDescription] = useState("");
  const [itemEdit, setItemEdit] = useState<MenuItemDraft | null>(null), [itemDirty, setItemDirty] = useState(false);
  const generation = useRef(0), abort = useRef<AbortController | null>(null), hasData = useRef(false); hasData.current = data.categories.length > 0;
  const categoryBaseline = categoryEdit === "new" ? "|" : categoryEdit ? `${categoryEdit.name}|${categoryEdit.description}` : "";
  const categoryDirty = Boolean(categoryEdit) && `${categoryName.trim()}|${categoryDescription.trim()}` !== categoryBaseline;
  const categoryGuard = useDirtyGuard(categoryDirty), itemSwitchGuard = useDirtyGuard(itemDirty);
  const c = locale === "tr" ? { subtitle: "Kategorileri, ürünleri ve seçenekleri yönetin.", categories: "Kategoriler", newCategory: "Yeni kategori", editCategory: "Kategoriyi düzenle", newItem: "Yeni ürün", selected: "seçili", bulkHint: "Toplu işlem için ürün seçin", available: "Satışta", unavailable: "Satış dışı", empty: "Bu kategoride ürün yok.", noCategories: "Başlamak için bir kategori ekleyin.", stale: "Önceki menü verileri gösteriliyor.", failed: "Menü yenilenemedi.", unknown: "İşlemin sonucu doğrulanamadı. Menü yenilendi; aynı işlemi açıkça yeniden deneyebilirsiniz.", retry: "İşlemi yeniden dene", discard: "Değişiklikler silinsin mi?", keep: "Düzenlemeye devam et", remove: "Sil", categoryName: "Kategori adı", description: "Açıklama" } : { subtitle: "Manage categories, items, and option groups.", categories: "Categories", newCategory: "New category", editCategory: "Edit category", newItem: "New item", selected: "selected", bulkHint: "Select items for bulk actions", available: "Available", unavailable: "Unavailable", empty: "There are no items in this category.", noCategories: "Add a category to get started.", stale: "The previous menu data is shown.", failed: "The menu could not be refreshed.", unknown: "The outcome could not be verified. The menu was reloaded; you can explicitly retry the same operation.", retry: "Retry operation", discard: "Discard changes?", keep: "Keep editing", remove: "Discard", categoryName: "Category name", description: "Description" };

  const load = useCallback(async (): Promise<MenuSnapshot | null> => {
    const request = ++generation.current; abort.current?.abort(); const controller = new AbortController(); abort.current = controller; setLoading(true); setError("");
    try { const snapshot = await restaurantManagementRepository.getMenu(controller.signal); if (request !== generation.current) return null; setData(snapshot); setSelectedCategory(current => snapshot.categories.some(x => x.id === current) ? current : snapshot.categories[0]?.id || ""); setSelectedItems([]); setStale(false); return snapshot; }
    catch { if (request === generation.current && !controller.signal.aborted) { setError(c.failed); setStale(hasData.current); } return null; }
    finally { if (request === generation.current) setLoading(false); }
  }, [c.failed]);
  useEffect(() => { void load(); return () => { generation.current += 1; abort.current?.abort(); }; }, [load]);
  const items = useMemo(() => data.items.filter(item => item.categoryId === selectedCategory).sort((a, b) => a.sortOrder - b.sortOrder), [data.items, selectedCategory]);

  async function mutation(key: string, run: (operationId: string) => Promise<unknown>, reached?: (snapshot: MenuSnapshot) => boolean): Promise<boolean> {
    if (busy) return false; setBusy(true); setError(""); setRetryAction(null); const operationId = stableManagementOperationId(key);
    try { await run(operationId); await load(); completeManagementIntent(key); return true; }
    catch { const snapshot = await load(); if (snapshot && reached?.(snapshot)) { completeManagementIntent(key); return true; } setError(c.unknown); setRetryAction(() => () => { void mutation(key, run, reached); }); return false; }
    finally { setBusy(false); }
  }
  function openCategory(value: MenuCategory | "new") { setCategoryEdit(value); setCategoryName(value === "new" ? "" : value.name); setCategoryDescription(value === "new" ? "" : value.description); }
  async function saveCategory() {
    const name = categoryName.trim(); if (!name || name.length > 120) return;
    const input = { ...(categoryEdit !== "new" && categoryEdit ? { id: categoryEdit.id } : {}), name, description: categoryDescription.trim(), icon: categoryEdit !== "new" && categoryEdit ? categoryEdit.icon : null, active: categoryEdit !== "new" && categoryEdit ? categoryEdit.active : true };
    const key = `category:${JSON.stringify(input)}`; const reached = input.id ? (snapshot: MenuSnapshot) => snapshot.categories.some(category => category.id === input.id && category.name === input.name && category.description === input.description && category.icon === input.icon && category.active === input.active) : undefined; if (await mutation(key, id => restaurantManagementRepository.saveCategory(input, id), reached)) setCategoryEdit(null);
  }
  function moveCategory(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= data.categories.length) return; const ids = data.categories.map(x => x.id); [ids[index], ids[target]] = [ids[target], ids[index]]; void mutation(`category-order:${ids.join(",")}`, id => restaurantManagementRepository.reorderCategories(ids, id), snapshot => snapshot.categories.map(category => category.id).join(",") === ids.join(",")); }
  function moveItem(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= items.length) return; const ids = items.map(x => x.id); [ids[index], ids[target]] = [ids[target], ids[index]]; void mutation(`item-order:${selectedCategory}:${ids.join(",")}`, id => restaurantManagementRepository.reorderItems(selectedCategory, ids, id), snapshot => snapshot.items.filter(item => item.categoryId === selectedCategory).sort((a, b) => a.sortOrder - b.sortOrder).map(item => item.id).join(",") === ids.join(",")); }
  function chooseCategory(id: string) { itemSwitchGuard.request(() => { setItemEdit(null); setSelectedCategory(id); setSelectedItems([]); }); }
  function editItem(item: MenuItem) { itemSwitchGuard.request(() => setItemEdit(draftFromItem(item, data))); }
  function newItem() { if (selectedCategory) itemSwitchGuard.request(() => setItemEdit({ name: "", description: "", imageUrl: "", price: "0.00", active: true, sortOrder: items.length, ingredients: [], groups: [] })); }

  return <Shell><PageHeader title={t.menu} subtitle={c.subtitle} action={<div className="page-header-actions"><Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw size={17} aria-hidden />{t.refresh}</Button><Button onClick={newItem} disabled={!selectedCategory}><Plus size={17} aria-hidden />{c.newItem}</Button></div>} />
    {error && <div className="ui-notice ui-notice--danger" role="alert"><span>{error}</span>{retryAction && <Button variant="secondary" disabled={busy} onClick={retryAction}>{c.retry}</Button>}</div>}{stale && <p className="ui-notice ui-notice--warning" role="status">{c.stale}</p>}
    {loading && !data.restaurantId && <div className="ui-card menu-loading" aria-busy="true">{t.loading}</div>}
    {!!data.restaurantId && <div className="menu-layout"><aside className="ui-card menu-categories" aria-label={c.categories}><div className="menu-panel-heading"><h2>{c.categories}</h2><Button variant="ghost" onClick={() => openCategory("new")}><Plus size={17} aria-hidden />{t.open}</Button></div>{data.categories.map((category, index) => <div className="menu-category" data-active={category.id === selectedCategory || undefined} key={category.id}><button className="menu-category__select" aria-pressed={category.id === selectedCategory} onClick={() => chooseCategory(category.id)}><strong>{category.name}</strong><small>{data.items.filter(item => item.categoryId === category.id).length}</small></button><Button variant="ghost" aria-label={`${c.editCategory}: ${category.name}`} onClick={() => openCategory(category)}><Pencil size={16} aria-hidden /></Button><Button variant="ghost" disabled={busy || index === 0} aria-label={`${category.name}: ${locale === "tr" ? "yukarı taşı" : "move up"}`} onClick={() => moveCategory(index, -1)}><ChevronUp size={16} aria-hidden /></Button><Button variant="ghost" disabled={busy || index === data.categories.length - 1} aria-label={`${category.name}: ${locale === "tr" ? "aşağı taşı" : "move down"}`} onClick={() => moveCategory(index, 1)}><ChevronDown size={16} aria-hidden /></Button></div>)}{!data.categories.length && <p>{c.noCategories}</p>}</aside>
      <section className="menu-workspace" aria-label={t.menu}><div className="ui-card menu-bulk"><span>{selectedItems.length ? `${selectedItems.length} ${c.selected}` : c.bulkHint}</span>{!!selectedItems.length && <><Button variant="ghost" disabled={busy} onClick={() => void mutation(`availability:${[...selectedItems].sort().join(",")}:true`, id => restaurantManagementRepository.setAvailability(selectedItems, true, id), snapshot => selectedItems.every(selected => snapshot.items.find(item => item.id === selected)?.active === true))}>{c.available}</Button><Button variant="secondary" disabled={busy} onClick={() => void mutation(`availability:${[...selectedItems].sort().join(",")}:false`, id => restaurantManagementRepository.setAvailability(selectedItems, false, id), snapshot => selectedItems.every(selected => snapshot.items.find(item => item.id === selected)?.active === false))}>{c.unavailable}</Button></>}</div><div className="menu-items">{items.map((item, index) => <article className="ui-card menu-item" key={item.id}><label className="menu-item__check"><input type="checkbox" checked={selectedItems.includes(item.id)} onChange={() => setSelectedItems(value => value.includes(item.id) ? value.filter(id => id !== item.id) : [...value, item.id])} /><span className="sr-only">{item.name}</span></label><div className="menu-item__media">{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <Utensils aria-hidden />}</div><div className="menu-item__body"><h3>{item.name}</h3>{item.description && <p>{item.description}</p>}<strong>{money(item.priceKurus, locale)}</strong><span className={item.active ? "success" : "muted"}>{item.active ? c.available : c.unavailable}</span></div><div className="menu-item__actions"><Button variant="ghost" aria-label={`${c.editCategory}: ${item.name}`} onClick={() => editItem(item)}><Pencil size={17} aria-hidden /></Button><Button variant="ghost" disabled={busy || index === 0} aria-label={`${item.name}: ${locale === "tr" ? "yukarı taşı" : "move up"}`} onClick={() => moveItem(index, -1)}><ChevronUp size={17} aria-hidden /></Button><Button variant="ghost" disabled={busy || index === items.length - 1} aria-label={`${item.name}: ${locale === "tr" ? "aşağı taşı" : "move down"}`} onClick={() => moveItem(index, 1)}><ChevronDown size={17} aria-hidden /></Button><Button variant={item.active ? "secondary" : "primary"} disabled={busy} onClick={() => void mutation(`availability:${item.id}:${!item.active}`, id => restaurantManagementRepository.setAvailability([item.id], !item.active, id), snapshot => snapshot.items.find(current => current.id === item.id)?.active === !item.active)}>{item.active ? c.unavailable : c.available}</Button></div></article>)}{!items.length && <div className="ui-card order-empty"><Utensils aria-hidden /><p>{c.empty}</p></div>}</div></section></div>}
    <Dialog open={Boolean(categoryEdit)} title={categoryEdit === "new" ? c.newCategory : c.editCategory} onClose={() => categoryGuard.request(() => setCategoryEdit(null))} actions={<><Button variant="secondary" onClick={() => categoryGuard.request(() => setCategoryEdit(null))}>{locale === "tr" ? "Kapat" : "Close"}</Button><Button disabled={busy || !categoryName.trim()} onClick={() => void saveCategory()}><Check size={17} aria-hidden />{t.save}</Button></>}><div className="form-grid"><FormField label={c.categoryName} maxLength={120} required value={categoryName} onChange={e => setCategoryName(e.target.value)} /><TextAreaField label={c.description} maxLength={1000} value={categoryDescription} onChange={e => setCategoryDescription(e.target.value)} /></div></Dialog>
    <Dialog open={categoryGuard.confirmOpen || itemSwitchGuard.confirmOpen} title={c.discard} onClose={() => { categoryGuard.cancel(); itemSwitchGuard.cancel(); }} actions={<><Button variant="secondary" onClick={() => { categoryGuard.cancel(); itemSwitchGuard.cancel(); }}>{c.keep}</Button><Button variant="danger" onClick={() => { categoryGuard.discard(); itemSwitchGuard.discard(); }}>{c.remove}</Button></>}><p>{locale === "tr" ? "Kaydedilmemiş değişiklikler kaybolacak." : "Unsaved changes will be lost."}</p></Dialog>
    <MenuItemDialog open={Boolean(itemEdit)} categoryId={selectedCategory} restaurantId={data.restaurantId} knownItemIds={data.items.map(item => item.id)} initial={itemEdit || undefined} onDirtyChange={setItemDirty} onSaved={load} onClose={() => setItemEdit(null)} />
  </Shell>;
}
