import { useCallback, useEffect, useRef, useState } from "react";
import type { MenuItemReactionAggregate, RestaurantReviewQueueItem, ReviewReportReason, ReviewReportStatus, ReviewVisibility } from "@hungrie/domain";
import { Shell } from "./Shell";
import { useLocale } from "./providers";
import { restaurantReviewV2Repository, RestaurantReviewRepositoryError } from "./reviewRepository";
import { CursorGate, REPORT_REASONS, StableReportOperation, validateOptionalNote } from "./reviewManagementModel";

const copy={
  en:{title:"Order reviews",intro:"Anonymous feedback from delivered Hungrie orders.",reviews:"Reviews",meal:"Meal feedback",visibility:"Visibility",reportStatus:"Report status",all:"All",published:"Published",hidden:"Hidden",open:"Open",resolved:"Resolved",dismissed:"Dismissed",taste:"Taste",speed:"Speed",items:"Ordered items",anonymous:"Anonymous customer",load:"Load more",retry:"Try again",empty:"No order reviews match these filters.",aggregateEmpty:"No meal reactions yet.",liked:"Liked",disliked:"Disliked",positive:"positive",report:"Report review",reportReason:"Reason",note:"Optional internal note",submit:"Submit report",submitting:"Submitting…",cancel:"Cancel",reported:"Reported",reportedHelp:"This report is read-only. Reporting does not hide a review or change its aggregates.",service:"Reviews are unavailable. Try again.",validation:"Use no more than 500 characters and remove unsupported control characters.",duplicate:"This review has already been reported.",privacy:"Customer identity and order details are never shown here."},
  tr:{title:"Sipariş değerlendirmeleri",intro:"Teslim edilen Hungrie siparişlerinden anonim geri bildirim.",reviews:"Değerlendirmeler",meal:"Yemek geri bildirimi",visibility:"Görünürlük",reportStatus:"Bildirim durumu",all:"Tümü",published:"Yayında",hidden:"Gizli",open:"Açık",resolved:"Çözüldü",dismissed:"Reddedildi",taste:"Lezzet",speed:"Hız",items:"Sipariş ürünleri",anonymous:"Anonim müşteri",load:"Daha fazla yükle",retry:"Tekrar dene",empty:"Bu filtrelere uyan sipariş değerlendirmesi yok.",aggregateEmpty:"Henüz yemek tepkisi yok.",liked:"Beğenildi",disliked:"Beğenilmedi",positive:"olumlu",report:"Değerlendirmeyi bildir",reportReason:"Neden",note:"İsteğe bağlı dahili not",submit:"Bildirimi gönder",submitting:"Gönderiliyor…",cancel:"İptal",reported:"Bildirildi",reportedHelp:"Bu bildirim salt okunurdur. Bildirmek değerlendirmeyi gizlemez veya toplamlarını değiştirmez.",service:"Değerlendirmeler kullanılamıyor. Tekrar deneyin.",validation:"En fazla 500 karakter kullanın ve desteklenmeyen kontrol karakterlerini kaldırın.",duplicate:"Bu değerlendirme zaten bildirilmiş.",privacy:"Müşteri kimliği ve sipariş ayrıntıları burada asla gösterilmez."}
} as const;
const reasonCopy={en:{spam:"Spam",abusive_content:"Abusive content",personal_information:"Personal information",not_related_to_order:"Not related to order",suspected_fraud:"Suspected fraud",other:"Other"},tr:{spam:"Spam",abusive_content:"Kötüye kullanım",personal_information:"Kişisel bilgi",not_related_to_order:"Siparişle ilgisiz",suspected_fraud:"Şüpheli dolandırıcılık",other:"Diğer"}} as const;

export function ReviewsPage(){
  const{locale}=useLocale(),c=copy[locale];
  const[tab,setTab]=useState<"reviews"|"meal">("reviews"),[rows,setRows]=useState<RestaurantReviewQueueItem[]>([]),[aggregates,setAggregates]=useState<MenuItemReactionAggregate[]>([]);
  const[visibility,setVisibility]=useState<ReviewVisibility|null>(null),[reportStatus,setReportStatus]=useState<ReviewReportStatus|null>(null);
  const[cursor,setCursor]=useState<string|null>(null),[aggregateCursor,setAggregateCursor]=useState<string|null>(null),[busy,setBusy]=useState(true),[moreBusy,setMoreBusy]=useState(false),[error,setError]=useState("");
  const[reporting,setReporting]=useState<RestaurantReviewQueueItem|null>(null),[reason,setReason]=useState<ReviewReportReason>("spam"),[note,setNote]=useState(""),[saving,setSaving]=useState(false);
  const reviewGate=useRef(new CursorGate()),aggregateGate=useRef(new CursorGate()),operation=useRef(new StableReportOperation());
  const fail=(value:unknown)=>setError(value instanceof RestaurantReviewRepositoryError&&value.code==="duplicate_report"?c.duplicate:c.service);
  const load=useCallback(async(reset=true)=>{const next=reset?null:cursor,token=reset?(reviewGate.current.reset(),reviewGate.current.begin(null)):reviewGate.current.begin(next);if(!token)return;reset?setBusy(true):setMoreBusy(true);setError("");try{const page=await restaurantReviewV2Repository.listReviews({status:visibility,reportStatus,cursor:next,limit:20});if(!reviewGate.current.finish(token,page.nextCursor))return;setRows(current=>{const source=reset?[]:current,map=new Map(source.map(row=>[row.reviewId,row]));page.items.forEach(row=>map.set(row.reviewId,row));return[...map.values()]});setCursor(page.nextCursor===next?null:page.nextCursor);}catch(value){reviewGate.current.fail(token);fail(value);}finally{setBusy(false);setMoreBusy(false)}},[cursor,visibility,reportStatus,c.service,c.duplicate]);
  const loadAggregates=useCallback(async(reset=true)=>{const next=reset?null:aggregateCursor,token=reset?(aggregateGate.current.reset(),aggregateGate.current.begin(null)):aggregateGate.current.begin(next);if(!token)return;reset?setBusy(true):setMoreBusy(true);setError("");try{const page=await restaurantReviewV2Repository.listReactionAggregates({cursor:next,limit:20});if(!aggregateGate.current.finish(token,page.nextCursor))return;setAggregates(current=>{const map=new Map((reset?[]:current).map(row=>[row.menuItemId,row]));page.items.forEach(row=>map.set(row.menuItemId,row));return[...map.values()]});setAggregateCursor(page.nextCursor===next?null:page.nextCursor);}catch(value){aggregateGate.current.fail(token);fail(value);}finally{setBusy(false);setMoreBusy(false)}},[aggregateCursor,c.service,c.duplicate]);
  useEffect(()=>{if(tab==="reviews")void load(true);else void loadAggregates(true)},[tab,visibility,reportStatus]);
  async function submitReport(event:React.FormEvent){event.preventDefault();if(!reporting)return;setError("");setSaving(true);try{const input=operation.current.prepare(reporting.reviewId,reason,validateOptionalNote(note));const result=await restaurantReviewV2Repository.reportReview(input);setRows(current=>current.map(row=>row.reviewId===result.reviewId?{...row,report:{reportId:result.reportId,reason,status:"open",createdAt:new Date().toISOString()}}:row));operation.current.clear();setReporting(null);setNote("");}catch(value){if(value instanceof Error&&value.message==="validation")setError(c.validation);else fail(value);}finally{setSaving(false)}}
  return <Shell><section className="review-workspace"><header className="review-header"><div><p className="eyebrow">Hungrie</p><h1>{c.title}</h1><p>{c.intro}</p></div><p className="privacy-note">🔒 {c.privacy}</p></header>
    <div className="review-tabs" role="tablist"><button role="tab" aria-selected={tab==="reviews"} onClick={()=>setTab("reviews")}>{c.reviews}</button><button role="tab" aria-selected={tab==="meal"} onClick={()=>setTab("meal")}>{c.meal}</button></div>
    {tab==="reviews"&&<><div className="review-filters"><label>{c.visibility}<select value={visibility??""} onChange={e=>setVisibility((e.target.value||null) as ReviewVisibility|null)}><option value="">{c.all}</option><option value="published">{c.published}</option><option value="hidden">{c.hidden}</option></select></label><label>{c.reportStatus}<select value={reportStatus??""} onChange={e=>setReportStatus((e.target.value||null) as ReviewReportStatus|null)}><option value="">{c.all}</option><option value="open">{c.open}</option><option value="resolved">{c.resolved}</option><option value="dismissed">{c.dismissed}</option></select></label></div>
      {busy?<ReviewSkeleton/>:<div className="review-list">{rows.map(row=><article className="review-card" key={row.reviewId}><div className="review-card-head"><strong>👤 {c.anonymous}</strong><span className={`status-chip status-${row.status}`}>{row.status==="published"?c.published:c.hidden}</span></div><div className="review-scores"><span>★ {row.overallRating.toFixed(1)}</span><span>{c.taste}: {row.tasteRating}/5</span><span>{c.speed}: {row.speedRating}/5</span></div>{row.comment&&<p className="review-comment">{row.comment}</p>}<p><strong>{c.items}:</strong> {row.items.map(item=>`${item.quantity}× ${item.name}`).join(", ")}</p><time>{new Date(row.createdAt).toLocaleDateString(locale)}</time>{row.report?<div className="report-state"><strong>{c.reported}: {reasonCopy[locale][row.report.reason]} · {copy[locale][row.report.status]}</strong><p>{c.reportedHelp}</p></div>:<button className="button report-button" onClick={()=>{setReporting(row);setReason("spam");setNote("")}}>{c.report}</button>}</article>)}</div>}{!busy&&!rows.length&&!error&&<p className="empty-state">{c.empty}</p>}{cursor&&<button className="load-more" disabled={moreBusy} onClick={()=>void load(false)}>{moreBusy?"…":c.load}</button>}</>}
    {tab==="meal"&&<>{busy?<ReviewSkeleton/>:<div className="aggregate-grid">{aggregates.map(row=><article className="aggregate-card" key={row.menuItemId}><h2>{row.menuItemName}</h2><dl><div><dt>👍 {c.liked}</dt><dd>{row.likedCount}</dd></div><div><dt>👎 {c.disliked}</dt><dd>{row.dislikedCount}</dd></div><div><dt>{c.positive}</dt><dd>{row.positivePercentage.toFixed(1)}%</dd></div></dl></article>)}</div>}{!busy&&!aggregates.length&&!error&&<p className="empty-state">{c.aggregateEmpty}</p>}{aggregateCursor&&<button className="load-more" disabled={moreBusy} onClick={()=>void loadAggregates(false)}>{moreBusy?"…":c.load}</button>}</>}
    {error&&<div className="review-error" role="alert"><span>{error}</span><button onClick={()=>void(tab==="reviews"?load(true):loadAggregates(true))}>{c.retry}</button></div>}
    {reporting&&<div className="modal-backdrop" role="presentation"><form className="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-title" onSubmit={submitReport}><h2 id="report-title">{c.report}</h2><label>{c.reportReason}<select value={reason} onChange={e=>setReason(e.target.value as ReviewReportReason)}>{REPORT_REASONS.map(value=><option key={value} value={value}>{reasonCopy[locale][value]}</option>)}</select></label><label>{c.note}<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/><small>{Array.from(note).length}/500</small></label><div className="dialog-actions"><button type="button" onClick={()=>setReporting(null)}>{c.cancel}</button><button className="button" disabled={saving} type="submit">{saving?c.submitting:c.submit}</button></div></form></div>}
  </section></Shell>;
}
function ReviewSkeleton(){return <div className="review-list" aria-label="Loading"><div className="review-card skeleton"/><div className="review-card skeleton"/></div>}
