import { useCallback, useEffect, useRef, useState } from "react";
import { Flag, LockKeyhole, ThumbsDown, ThumbsUp, UserRound } from "lucide-react";
import type { MenuItemReactionAggregate, RestaurantReviewQueueItem, ReviewReportReason, ReviewReportStatus, ReviewVisibility } from "@hungrie/domain";
import { Shell } from "./Shell";
import { useLocale } from "./providers";
import { Button } from "./components/Button";
import { Dialog } from "./components/Dialog";
import { PageHeader } from "./components/PageHeader";
import { handleTabKeyboard } from "./components/tabKeyboard";
import { restaurantReviewV2Repository, RestaurantReviewRepositoryError } from "./reviewRepository";
import { CursorGate, REPORT_REASONS, StableReportOperation, validateOptionalNote } from "./reviewManagementModel";

const copy={
  en:{title:"Reviews",intro:"Anonymous feedback from delivered Hungrie orders.",reviews:"Order reviews",meal:"Meal feedback",visibility:"Visibility",reportStatus:"Report status",all:"All",published:"Published",hidden:"Hidden",open:"Open",resolved:"Resolved",dismissed:"Dismissed",taste:"Taste",speed:"Speed",items:"Ordered items",anonymous:"Anonymous customer",load:"Load more",retry:"Try again",empty:"No order reviews match these filters.",aggregateEmpty:"No meal reactions yet.",liked:"Liked",disliked:"Disliked",positive:"Positive",report:"Report review",reportReason:"Reason",note:"Optional internal note",submit:"Submit report",submitting:"Submitting…",cancel:"Cancel",reported:"Reported",reportedHelp:"Reporting is read-only. It does not hide or modify this review or its aggregates.",service:"Reviews are unavailable. Try again.",validation:"Use no more than 500 characters and remove unsupported control characters.",duplicate:"This review has already been reported.",unknown:"The report result could not be verified. Authoritative data was reloaded; retry submits the same operation.",privacy:"Customer identity and order details are never shown here.",loading:"Loading anonymous reviews…",offline:"Offline. Previously loaded reviews remain visible.",stale:"The latest refresh failed. Previously loaded reviews may be stale.",characters:"characters"},
  tr:{title:"Değerlendirmeler",intro:"Teslim edilen Hungrie siparişlerinden anonim geri bildirim.",reviews:"Sipariş değerlendirmeleri",meal:"Yemek geri bildirimi",visibility:"Görünürlük",reportStatus:"Bildirim durumu",all:"Tümü",published:"Yayında",hidden:"Gizli",open:"Açık",resolved:"Çözüldü",dismissed:"Reddedildi",taste:"Lezzet",speed:"Hız",items:"Sipariş ürünleri",anonymous:"Anonim müşteri",load:"Daha fazla yükle",retry:"Tekrar dene",empty:"Bu filtrelere uyan sipariş değerlendirmesi yok.",aggregateEmpty:"Henüz yemek tepkisi yok.",liked:"Beğenildi",disliked:"Beğenilmedi",positive:"Olumlu",report:"Değerlendirmeyi bildir",reportReason:"Neden",note:"İsteğe bağlı dahili not",submit:"Bildirimi gönder",submitting:"Gönderiliyor…",cancel:"İptal",reported:"Bildirildi",reportedHelp:"Bildirim salt okunurdur. Değerlendirmeyi veya toplamlarını gizlemez ya da değiştirmez.",service:"Değerlendirmeler kullanılamıyor. Tekrar deneyin.",validation:"En fazla 500 karakter kullanın ve desteklenmeyen kontrol karakterlerini kaldırın.",duplicate:"Bu değerlendirme zaten bildirilmiş.",unknown:"Bildirim sonucu doğrulanamadı. Yetkili veri yeniden yüklendi; tekrar deneme aynı işlemi gönderir.",privacy:"Müşteri kimliği ve sipariş ayrıntıları burada asla gösterilmez.",loading:"Anonim değerlendirmeler yükleniyor…",offline:"Çevrimdışı. Daha önce yüklenen değerlendirmeler gösterilmeye devam ediyor.",stale:"Son yenileme başarısız. Önceki değerlendirmeler güncel olmayabilir.",characters:"karakter"}
} as const;
const reasonCopy={en:{spam:"Spam",abusive_content:"Abusive content",personal_information:"Personal information",not_related_to_order:"Not related to order",suspected_fraud:"Suspected fraud",other:"Other"},tr:{spam:"Spam",abusive_content:"Kötüye kullanım",personal_information:"Kişisel bilgi",not_related_to_order:"Siparişle ilgisiz",suspected_fraud:"Şüpheli dolandırıcılık",other:"Diğer"}} as const;

export function ReviewsPage(){
  const{locale}=useLocale(),c=copy[locale];
  const[tab,setTab]=useState<"reviews"|"meal">("reviews"),[rows,setRows]=useState<RestaurantReviewQueueItem[]>([]),[aggregates,setAggregates]=useState<MenuItemReactionAggregate[]>([]);
  const[visibility,setVisibility]=useState<ReviewVisibility|null>(null),[reportStatus,setReportStatus]=useState<ReviewReportStatus|null>(null),[cursor,setCursor]=useState<string|null>(null),[aggregateCursor,setAggregateCursor]=useState<string|null>(null);
  const[busy,setBusy]=useState(true),[moreBusy,setMoreBusy]=useState(false),[error,setError]=useState(""),[stale,setStale]=useState(false),[online,setOnline]=useState(typeof navigator==="undefined"?true:navigator.onLine);
  const[reporting,setReporting]=useState<RestaurantReviewQueueItem|null>(null),[reason,setReason]=useState<ReviewReportReason>("spam"),[note,setNote]=useState(""),[saving,setSaving]=useState(false),[reportError,setReportError]=useState("");
  const reviewGate=useRef(new CursorGate()),aggregateGate=useRef(new CursorGate()),operation=useRef(new StableReportOperation());
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update)}},[]);

  const fail=useCallback((value:unknown)=>setError(value instanceof RestaurantReviewRepositoryError&&value.code==="duplicate_report"?c.duplicate:c.service),[c]);
  const load=useCallback(async(reset=true)=>{if(!online){setBusy(false);setStale(rows.length>0);return null;}const next=reset?null:cursor,token=reset?(reviewGate.current.reset(),reviewGate.current.begin(null)):reviewGate.current.begin(next);if(!token)return null;reset?setBusy(true):setMoreBusy(true);setError("");try{const page=await restaurantReviewV2Repository.listReviews({status:visibility,reportStatus,cursor:next,limit:20});if(!reviewGate.current.finish(token,page.nextCursor))return null;setRows(current=>{const map=new Map((reset?[]:current).map(row=>[row.reviewId,row]));page.items.forEach(row=>map.set(row.reviewId,row));return[...map.values()]});setCursor(page.nextCursor===next?null:page.nextCursor);setStale(false);return page;}catch(value){reviewGate.current.fail(token);fail(value);setStale(rows.length>0);return null;}finally{setBusy(false);setMoreBusy(false)}},[cursor,visibility,reportStatus,online,rows.length,fail]);
  const loadAggregates=useCallback(async(reset=true)=>{if(!online){setBusy(false);setStale(aggregates.length>0);return;}const next=reset?null:aggregateCursor,token=reset?(aggregateGate.current.reset(),aggregateGate.current.begin(null)):aggregateGate.current.begin(next);if(!token)return;reset?setBusy(true):setMoreBusy(true);setError("");try{const page=await restaurantReviewV2Repository.listReactionAggregates({cursor:next,limit:20});if(!aggregateGate.current.finish(token,page.nextCursor))return;setAggregates(current=>{const map=new Map((reset?[]:current).map(row=>[row.menuItemId,row]));page.items.forEach(row=>map.set(row.menuItemId,row));return[...map.values()]});setAggregateCursor(page.nextCursor===next?null:page.nextCursor);setStale(false);}catch(value){aggregateGate.current.fail(token);fail(value);setStale(aggregates.length>0);}finally{setBusy(false);setMoreBusy(false)}},[aggregateCursor,online,aggregates.length,fail]);
  useEffect(()=>{if(tab==="reviews")void load(true);else void loadAggregates(true)},[tab,visibility,reportStatus,online]);

  const closeReport=()=>{if(saving)return;setReporting(null);setReportError("");};
  async function findAuthoritativeReport(reviewId:string){let next:string|null=null;const seen=new Set<string>();for(let pageNumber=0;pageNumber<20;pageNumber+=1){const page=await restaurantReviewV2Repository.listReviews({status:visibility,reportStatus:"open",cursor:next,limit:50});const match=page.items.find(row=>row.reviewId===reviewId&&row.report);if(match)return match;if(!page.nextCursor||seen.has(page.nextCursor))return null;seen.add(page.nextCursor);next=page.nextCursor;}return null;}
  async function submitReport(event:React.FormEvent){event.preventDefault();if(!reporting||saving)return;setReportError("");setSaving(true);try{const input=operation.current.prepare(reporting.reviewId,reason,validateOptionalNote(note));await restaurantReviewV2Repository.reportReview(input);const authoritative=await findAuthoritativeReport(reporting.reviewId);if(!authoritative)throw new Error("unverified");setRows(current=>current.map(row=>row.reviewId===authoritative.reviewId?authoritative:row));operation.current.clear();setReporting(null);setNote("");}catch(value){if(value instanceof Error&&value.message==="validation"){setReportError(c.validation);}else{const authoritative=await findAuthoritativeReport(reporting.reviewId).catch(()=>null);if(authoritative){setRows(current=>current.map(row=>row.reviewId===authoritative.reviewId?authoritative:row));operation.current.clear();setReporting(null);setNote("");}else setReportError(value instanceof RestaurantReviewRepositoryError&&value.code==="duplicate_report"?c.duplicate:c.unknown);}}finally{setSaving(false)}}
  const openReport=(row:RestaurantReviewQueueItem)=>{setReporting(row);setReason("spam");setNote("");setReportError("")};

  return <Shell><section className="review-workspace"><PageHeader title={c.title} subtitle={c.intro} action={<p className="privacy-note"><LockKeyhole size={18} aria-hidden="true"/>{c.privacy}</p>}/>
    <div className="review-tabs" role="tablist" aria-label={c.title} onKeyDown={handleTabKeyboard}><button id="reviews-tab" role="tab" aria-controls="reviews-panel" aria-selected={tab==="reviews"} tabIndex={tab==="reviews"?0:-1} onClick={()=>setTab("reviews")}>{c.reviews}</button><button id="meal-tab" role="tab" aria-controls="meal-panel" aria-selected={tab==="meal"} tabIndex={tab==="meal"?0:-1} onClick={()=>setTab("meal")}>{c.meal}</button></div>
    {!online&&<p className="ui-notice ui-notice--warning" role="status">{c.offline}</p>}{stale&&<p className="ui-notice ui-notice--warning" role="alert">{c.stale}</p>}
    {tab==="reviews"&&<div id="reviews-panel" role="tabpanel" aria-labelledby="reviews-tab"><div className="review-filters"><label><span>{c.visibility}</span><select value={visibility??""} onChange={e=>setVisibility((e.target.value||null) as ReviewVisibility|null)}><option value="">{c.all}</option><option value="published">{c.published}</option><option value="hidden">{c.hidden}</option></select></label><label><span>{c.reportStatus}</span><select value={reportStatus??""} onChange={e=>setReportStatus((e.target.value||null) as ReviewReportStatus|null)}><option value="">{c.all}</option><option value="open">{c.open}</option><option value="resolved">{c.resolved}</option><option value="dismissed">{c.dismissed}</option></select></label></div>
      {busy&&!rows.length?<ReviewSkeleton label={c.loading}/>:<div className="review-list">{rows.map(row=><article className="ui-card review-card" key={row.reviewId}><div className="review-card-head"><strong><UserRound size={18} aria-hidden="true"/> {c.anonymous}</strong><span className={`ui-chip status-${row.status}`}>{row.status==="published"?c.published:c.hidden}</span></div><div className="review-scores"><span>★ {row.overallRating.toFixed(1)}</span><span>{c.taste}: {row.tasteRating}/5</span><span>{c.speed}: {row.speedRating}/5</span></div>{row.comment&&<blockquote className="review-comment">{row.comment}</blockquote>}<p><strong>{c.items}:</strong> {row.items.map(item=>`${item.quantity}× ${item.name}`).join(", ")}</p><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleDateString(locale)}</time>{row.report?<div className="report-state"><strong>{c.reported}: {reasonCopy[locale][row.report.reason]} · {copy[locale][row.report.status]}</strong><p>{c.reportedHelp}</p></div>:<Button variant="secondary" icon={<Flag size={17} aria-hidden="true"/>} className="report-button" onClick={()=>openReport(row)}>{c.report}</Button>}</article>)}</div>}{!busy&&!rows.length&&!error&&<p className="ui-card empty-state">{c.empty}</p>}{cursor&&<Button variant="secondary" className="load-more" disabled={moreBusy||!online} onClick={()=>void load(false)}>{moreBusy?c.loading:c.load}</Button>}</div>}
    {tab==="meal"&&<div id="meal-panel" role="tabpanel" aria-labelledby="meal-tab">{busy&&!aggregates.length?<ReviewSkeleton label={c.loading}/>:<div className="aggregate-grid">{aggregates.map(row=><article className="ui-card aggregate-card" key={row.menuItemId}><h2>{row.menuItemName}</h2><dl><div><dt><ThumbsUp size={17} aria-hidden="true"/> {c.liked}</dt><dd>{row.likedCount}</dd></div><div><dt><ThumbsDown size={17} aria-hidden="true"/> {c.disliked}</dt><dd>{row.dislikedCount}</dd></div><div><dt>{c.positive}</dt><dd>{row.positivePercentage.toFixed(1)}%</dd></div></dl></article>)}</div>}{!busy&&!aggregates.length&&!error&&<p className="ui-card empty-state">{c.aggregateEmpty}</p>}{aggregateCursor&&<Button variant="secondary" className="load-more" disabled={moreBusy||!online} onClick={()=>void loadAggregates(false)}>{moreBusy?c.loading:c.load}</Button>}</div>}
    {error&&<div className="ui-notice ui-notice--danger review-error" role="alert"><span>{error}</span><Button variant="secondary" onClick={()=>void(tab==="reviews"?load(true):loadAggregates(true))}>{c.retry}</Button></div>}
    <Dialog open={Boolean(reporting)} title={c.report} onClose={closeReport} actions={<><Button variant="secondary" type="button" disabled={saving} onClick={closeReport}>{c.cancel}</Button><Button form="review-report-form" disabled={saving} type="submit">{saving?c.submitting:c.submit}</Button></>}><form id="review-report-form" className="report-form" onSubmit={submitReport}><label><span>{c.reportReason}</span><select value={reason} disabled={saving} onChange={e=>setReason(e.target.value as ReviewReportReason)}>{REPORT_REASONS.map(value=><option key={value} value={value}>{reasonCopy[locale][value]}</option>)}</select></label><label><span>{c.note}</span><textarea maxLength={500} disabled={saving} value={note} aria-describedby="report-note-count report-error" onChange={e=>setNote(e.target.value)}/><small id="report-note-count">{Array.from(note).length}/500 {c.characters}</small></label>{reportError&&<p id="report-error" className="ui-notice ui-notice--danger" role="alert">{reportError}</p>}</form></Dialog>
  </section></Shell>;
}
function ReviewSkeleton({label}:{label:string}){return <div className="review-list" aria-label={label} aria-busy="true"><div className="ui-card review-card skeleton"/><div className="ui-card review-card skeleton"/></div>}
