import { Link, useRouter } from "expo-router";
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, LockKeyhole, Mail, ShieldX, Store } from "lucide-react-native";
import { useState } from "react";
import { Pressable, StyleSheet, useWindowDimensions, View } from "react-native";
import { colors, radius, shadow } from "../theme";
import { AppText, Button, Card, Field } from "../ui";

const copy = {
  tr: { welcome: "Restoran paneline hoş geldiniz", hint: "Siparişleri yönetin, menünüzü güncelleyin ve işletmenizi takip edin.", email: "E-posta", password: "Şifre", login: "Giriş yap", forgot: "Şifremi unuttum", invite: "Davet bağlantınız mı var?", accept: "Daveti kabul et", resetTitle: "Şifrenizi yenileyin", resetHint: "E-posta adresinizi girin. Şifre yenileme bağlantısı göndereceğiz.", send: "Bağlantı gönder", sent: "Bağlantı gönderildi", back: "Girişe dön", invitation: "Restoran daveti", newAccount: "Yeni hesap", existing: "Mevcut hesap", verify: "E-postanızı doğrulayın, ardından davet bağlantısını yeniden açın.", continue: "Devam et" },
  en: { welcome: "Welcome to your Restaurant workspace", hint: "Manage orders, update your menu, and keep your business moving.", email: "Email", password: "Password", login: "Sign in", forgot: "Forgot password?", invite: "Have an invitation link?", accept: "Accept invitation", resetTitle: "Reset your password", resetHint: "Enter your email and we will send a password-reset link.", send: "Send reset link", sent: "Reset link sent", back: "Back to sign in", invitation: "Restaurant invitation", newAccount: "New account", existing: "Existing account", verify: "Verify your email, then reopen the invitation link.", continue: "Continue" },
};

function AccessFrame({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) {
  const { width } = useWindowDimensions();
  return <View style={styles.page}><View style={[styles.hero, width < 768 && styles.heroMobile]}><View style={styles.logo}><AppText weight="bold" style={{ color: colors.white, fontSize: 27 }}>H</AppText></View><View style={{ maxWidth: 470 }}><AppText style={styles.heroBrand} weight="bold">Hungrie Restaurant</AppText><AppText style={styles.heroTitle} weight="bold">{title}</AppText><AppText style={styles.heroHint}>{subtitle}</AppText></View><View style={styles.heroGlow} /></View><View style={styles.formSide}>{children}<AppText style={styles.mockNote}>UI mock · No account or network connection is used</AppText></View></View>;
}

export function LoginScreen() {
  const [locale, setLocale] = useState<"tr" | "en">("tr"); const [email, setEmail] = useState("owner@restaurant.example"); const [password, setPassword] = useState("mock-password"); const c = copy[locale]; const router = useRouter();
  return <AccessFrame title={c.welcome} subtitle={c.hint}><Card style={styles.formCard}><View style={styles.formTop}><View style={styles.formIcon}><Store size={23} color={colors.orange} /></View><Pressable onPress={() => setLocale(locale === "tr" ? "en" : "tr")} style={styles.lang}><AppText weight="bold">{locale.toUpperCase()}</AppText></Pressable></View><AppText style={styles.formTitle} weight="bold">{c.login}</AppText><Field label={c.email} value={email} onChangeText={setEmail} /><Field label={c.password} value={password} onChangeText={setPassword} /><Button label={c.login} onPress={() => router.replace("/dashboard" as never)} /><Link href="/forgot-password" asChild><Pressable style={styles.textButton}><AppText weight="medium" style={{ color: colors.orange }}>{c.forgot}</AppText></Pressable></Link><View style={styles.divider} /><AppText style={{ textAlign: "center", color: colors.muted }}>{c.invite}</AppText><Link href="/invite" asChild><Pressable style={styles.outlineLink}><Mail size={17} color={colors.ink} /><AppText weight="bold">{c.accept}</AppText></Pressable></Link></Card></AccessFrame>;
}

export function ForgotPasswordScreen() {
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const c = copy.en;
  return <AccessFrame title={c.resetTitle} subtitle={c.resetHint}><Card style={styles.formCard}>{sent ? <View style={styles.success}><CheckCircle2 size={42} color={colors.green} /><AppText style={styles.formTitle} weight="bold">{c.sent}</AppText><AppText style={{ textAlign: "center", color: colors.muted }}>{c.resetHint}</AppText></View> : <><View style={styles.formIcon}><LockKeyhole size={23} color={colors.orange} /></View><AppText style={styles.formTitle} weight="bold">{c.resetTitle}</AppText><Field label={c.email} value={email} onChangeText={setEmail} /><Button label={c.send} onPress={() => setSent(true)} /></>}<Link href="/login" asChild><Pressable style={styles.textButton}><ArrowLeft size={16} color={colors.orange} /><AppText weight="medium" style={{ color: colors.orange }}>{c.back}</AppText></Pressable></Link></Card></AccessFrame>;
}

export function InviteScreen() {
  const [mode, setMode] = useState<"new" | "existing">("new"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const c = copy.en;
  return <AccessFrame title={c.invitation} subtitle="Osteria Mezzaluna invited you to manage its Hungrie workspace."><Card style={styles.formCard}><View style={styles.segment}><Pressable onPress={() => setMode("new")} style={[styles.segmentButton, mode === "new" && styles.segmentActive]}><AppText weight="bold" style={mode === "new" ? { color: colors.white } : undefined}>{c.newAccount}</AppText></Pressable><Pressable onPress={() => setMode("existing")} style={[styles.segmentButton, mode === "existing" && styles.segmentActive]}><AppText weight="bold" style={mode === "existing" ? { color: colors.white } : undefined}>{c.existing}</AppText></Pressable></View><Field label={c.email} value={email} onChangeText={setEmail} /><Field label={c.password} value={password} onChangeText={setPassword} /><Button label={c.continue} /><View style={styles.verify}><Mail size={18} color={colors.blue} /><AppText style={{ flex: 1 }}>{c.verify}</AppText></View></Card></AccessFrame>;
}

export function AccessStateScreen({ kind }: { kind: "checking" | "error" | "pending" | "suspended" | "revoked" | "wrong-role" | "session" }) {
  const content = {
    checking: ["Checking Restaurant access…", "We are confirming your account and Restaurant assignment."], error: ["Restaurant services are unavailable", "Try again. Your protected data has not been loaded."], pending: ["Approval is pending", "An Admin must approve this Restaurant account before it can accept orders."], suspended: ["Restaurant access is suspended", "Contact support or your account owner for assistance."], revoked: ["Access was revoked", "This account no longer has access to the Restaurant workspace."], "wrong-role": ["This is not a Restaurant account", "Use the application assigned to your account type."], session: ["Your session expired", "Sign in again to continue securely."],
  }[kind];
  const Icon = kind === "pending" || kind === "checking" ? Clock3 : kind === "error" ? AlertTriangle : ShieldX;
  return <View style={styles.statePage}><Card style={styles.stateCard}><View style={[styles.stateIcon, kind === "pending" && { backgroundColor: colors.amberSoft }]}><Icon size={34} color={kind === "pending" ? colors.amber : colors.red} /></View><AppText style={styles.stateTitle} weight="bold">{content[0]}</AppText><AppText style={styles.stateText}>{content[1]}</AppText>{kind === "error" || kind === "checking" ? <Button label="Try again" /> : <Link href="/login" asChild><Pressable style={styles.outlineLink}><AppText weight="bold">Return to sign in</AppText></Pressable></Link>}</Card></View>;
}

const styles = StyleSheet.create({
  page: { minHeight: "100%", flex: 1, flexDirection: "row", backgroundColor: colors.canvas, flexWrap: "wrap" }, hero: { flex: 1.05, minWidth: 420, minHeight: 620, backgroundColor: colors.ink, padding: 64, justifyContent: "center", gap: 34, overflow: "hidden" }, heroMobile: { minWidth: "100%", minHeight: 280, padding: 28 }, logo: { width: 54, height: 54, borderRadius: 18, backgroundColor: colors.orange, alignItems: "center", justifyContent: "center" }, heroBrand: { color: colors.orange, fontSize: 18, marginBottom: 22 }, heroTitle: { color: colors.white, fontSize: 42, lineHeight: 48, marginBottom: 14 }, heroHint: { color: "#B8C0D0", fontSize: 18, lineHeight: 27 }, heroGlow: { position: "absolute", width: 360, height: 360, borderRadius: 180, backgroundColor: "rgba(255,101,32,.10)", right: -130, bottom: -130 }, formSide: { flex: .95, minWidth: 340, alignItems: "center", justifyContent: "center", padding: 28 }, formCard: { width: "100%", maxWidth: 470, gap: 16, padding: 28 }, formTop: { flexDirection: "row", justifyContent: "space-between" }, formIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.orangeSoft, alignItems: "center", justifyContent: "center" }, lang: { minWidth: 44, height: 44, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: 13 }, formTitle: { fontSize: 26, marginVertical: 4 }, textButton: { minHeight: 44, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center" }, outlineLink: { minHeight: 48, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, divider: { height: 1, backgroundColor: colors.border }, mockNote: { marginTop: 16, color: colors.muted, fontSize: 12, textAlign: "center" }, success: { alignItems: "center", gap: 12, paddingVertical: 18 }, segment: { flexDirection: "row", padding: 4, backgroundColor: colors.canvas, borderRadius: radius.md }, segmentButton: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", borderRadius: 10 }, segmentActive: { backgroundColor: colors.ink }, verify: { flexDirection: "row", gap: 10, padding: 13, borderRadius: radius.md, backgroundColor: colors.blueSoft }, statePage: { flex: 1, backgroundColor: colors.canvas, alignItems: "center", justifyContent: "center", padding: 22 }, stateCard: { width: "100%", maxWidth: 520, alignItems: "center", gap: 15, padding: 34, ...shadow }, stateIcon: { width: 70, height: 70, borderRadius: 24, backgroundColor: colors.redSoft, alignItems: "center", justifyContent: "center" }, stateTitle: { fontSize: 27, textAlign: "center" }, stateText: { color: colors.muted, textAlign: "center", maxWidth: 390, marginBottom: 8 },
});
