import { AlertTriangle, CheckCircle2, Mail, Plus, ShieldAlert, UserRound, Users } from "lucide-react-native";
import { useState } from "react";
import { StyleSheet, useWindowDimensions, View } from "react-native";
import { getCopy } from "../copy";
import { incidents, staff } from "../fixtures";
import { useMock } from "../mock-context";
import { AppShell } from "../shell";
import { breakpoints, colors, radius } from "../theme";
import { AppText, Button, Card, Chip, Dialog, Field, ListRow, PageHeader } from "../ui";

function ConceptNotice() { const { locale } = useMock(); const c = getCopy(locale); return <View style={styles.notice}><ShieldAlert size={18} color={colors.amber} /><AppText style={{ flex: 1, color: colors.amber }} weight="medium">{c.future}. {locale === "tr" ? "Bu ekran yalnızca görsel değerlendirme içindir." : "This screen is for visual evaluation only."}</AppText></View>; }

export function StaffScreen() {
  const { locale } = useMock(); const c = getCopy(locale); const { width } = useWindowDimensions(); const stacked = width < breakpoints.desktop; const [invite, setInvite] = useState(false); const [email, setEmail] = useState(""); const [revoke, setRevoke] = useState<string | null>(null);
  return <AppShell><PageHeader title={c.staff} subtitle={locale === "tr" ? "Sahip ve yönetici erişimi konsepti." : "Owner and manager access concept."} action={<Button label={locale === "tr" ? "Ekip üyesi davet et" : "Invite staff member"} icon={Plus} onPress={() => setInvite(true)} />} /><ConceptNotice /><View style={[styles.grid, stacked && styles.gridStacked]}><Card style={[{ flex: 1.3 }, stacked && styles.panelStacked]}><View style={styles.heading}><View><AppText weight="bold" style={styles.title}>{locale === "tr" ? "Ekip üyeleri" : "Team members"}</AppText><AppText style={styles.muted}>{staff.length} {locale === "tr" ? "kayıt" : "records"}</AppText></View><Users size={23} color={colors.orange} /></View>{staff.map(member => <ListRow key={member.id} title={member.name} subtitle={`${member.email} · ${member.role}`} icon={UserRound} trailing={<View style={styles.memberAction}><Chip label={member.state === "active" ? (locale === "tr" ? "Aktif" : "Active") : (locale === "tr" ? "Bekliyor" : "Pending")} tone={member.state === "active" ? "success" : "warning"} /><Button label={locale === "tr" ? "Kaldır" : "Remove"} variant="secondary" compact onPress={() => setRevoke(member.id)} /></View>} />)}</Card><Card style={[{ flex: 1 }, stacked && styles.panelStacked]}><AppText weight="bold" style={styles.title}>{locale === "tr" ? "Rol özeti" : "Role summary"}</AppText><View style={styles.role}><AppText weight="bold">Owner</AppText><AppText style={styles.muted}>{locale === "tr" ? "Restoran ve erişim ayarları" : "Restaurant and access settings"}</AppText></View><View style={styles.role}><AppText weight="bold">Manager</AppText><AppText style={styles.muted}>{locale === "tr" ? "Sipariş ve menü işlemleri" : "Order and menu operations"}</AppText></View></Card></View><Dialog visible={invite} title={locale === "tr" ? "Ekip üyesi davet et" : "Invite staff member"} onClose={() => setInvite(false)} actions={<><Button label={c.cancel} variant="secondary" onPress={() => setInvite(false)} /><Button label={locale === "tr" ? "Daveti gönder" : "Send invitation"} disabled={!email.includes("@")} onPress={() => setInvite(false)} /></>}><Field label={locale === "tr" ? "E-posta" : "Email"} value={email} onChangeText={setEmail} /><View style={styles.role}><AppText weight="bold">Manager</AppText><AppText style={styles.muted}>{locale === "tr" ? "Konsept rol — izin sözleşmesi gerekli" : "Concept role — permission contract required"}</AppText></View></Dialog><Dialog visible={Boolean(revoke)} title={locale === "tr" ? "Ekip erişimi kaldırılsın mı?" : "Remove staff access?"} onClose={() => setRevoke(null)} actions={<><Button label={c.cancel} variant="secondary" onPress={() => setRevoke(null)} /><Button label={locale === "tr" ? "Erişimi kaldır" : "Remove access"} variant="danger" onPress={() => setRevoke(null)} /></>}><AppText>{locale === "tr" ? "Bu yalnızca yerel bir UI önizlemesidir." : "This is only a local UI preview."}</AppText></Dialog></AppShell>;
}

export function IncidentsScreen() {
  const { locale } = useMock(); const c = getCopy(locale); const { width } = useWindowDimensions(); const stacked = width < breakpoints.desktop; const [selected, setSelected] = useState(incidents[0]); const [note, setNote] = useState("");
  return <AppShell><PageHeader title={c.incidents} subtitle={locale === "tr" ? "Operasyon uyarıları ve takip konsepti." : "Operational alert and follow-up concept."} /><ConceptNotice /><View style={[styles.grid, stacked && styles.gridStacked]}><Card style={[{ flex: 1 }, stacked && styles.panelStacked]}><AppText weight="bold" style={styles.title}>{locale === "tr" ? "Olaylar" : "Incidents"}</AppText>{incidents.map(incident => <ListRow key={incident.id} title={incident.title} subtitle={incident.openedAt} icon={incident.state === "resolved" ? CheckCircle2 : AlertTriangle} onPress={() => setSelected(incident)} trailing={<Chip label={incident.state} tone={incident.state === "resolved" ? "success" : "danger"} />} />)}</Card><Card style={[{ flex: 1.2, gap: 14 }, stacked && styles.panelStacked]}><View style={styles.heading}><View style={{ flex: 1 }}><AppText style={styles.muted} weight="bold">{selected.id.toUpperCase()}</AppText><AppText weight="bold" style={styles.title}>{selected.title}</AppText></View><Chip label={selected.state} tone={selected.state === "resolved" ? "success" : "danger"} /></View><AppText>{selected.details}</AppText><View style={styles.snapshot}><AppText weight="bold">{locale === "tr" ? "Eşik anlık görüntüsü" : "Threshold snapshot"}</AppText><AppText style={styles.muted}>Eligible: 5 · Expired: 3 · Non-response: 60%</AppText></View><Field label={locale === "tr" ? "Çözüm notu" : "Resolution note"} value={note} onChangeText={setNote} multiline /><View style={styles.actions}><Button label={locale === "tr" ? "Alındı olarak işaretle" : "Acknowledge"} variant="secondary" /><Button label={locale === "tr" ? "Çözüldü olarak işaretle" : "Resolve"} disabled={!note.trim()} /></View></Card></View></AppShell>;
}

const styles = StyleSheet.create({ notice: { flexDirection: "row", gap: 10, padding: 13, borderRadius: radius.md, backgroundColor: colors.amberSoft, marginBottom: 16 }, range: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 16 }, metric: { flex: 1, minWidth: 210, gap: 7 }, metricIcon: { width: 43, height: 43, borderRadius: 14, alignItems: "center", justifyContent: "center" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 16, alignItems: "flex-start" }, gridStacked: { flexDirection: "column", flexWrap: "nowrap", width: "100%" }, panelStacked: { flexGrow: 0, flexShrink: 0, flexBasis: "auto", width: "100%", minWidth: 0 }, title: { fontSize: 19 }, muted: { color: colors.muted, fontSize: 13 }, heading: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 8 }, memberAction: { flexDirection: "row", alignItems: "center", gap: 7, flexWrap: "wrap", justifyContent: "flex-end" }, role: { padding: 13, borderRadius: radius.md, backgroundColor: colors.canvas, marginTop: 10, gap: 3 }, snapshot: { borderRadius: radius.md, padding: 13, backgroundColor: colors.blueSoft, gap: 4 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 9, justifyContent: "flex-end" },
});
