import { Bell, CheckCircle2, Clock3, PackageCheck, ShoppingBag, TrendingUp, Wifi } from "lucide-react-native";
import { StyleSheet, useWindowDimensions, View } from "react-native";
import { getCopy } from "../copy";
import { useMock } from "../mock-context";
import { money, ResponsiveOrders } from "../order-ui";
import { AppShell } from "../shell";
import { breakpoints, colors, radius } from "../theme";
import { AppText, Button, Card, PageHeader, StateBoundary, Toggle } from "../ui";

export function DashboardScreen() {
  const { locale, accepting, setAccepting, orders } = useMock(); const c = getCopy(locale); const { width } = useWindowDimensions(); const compact = width < breakpoints.phone; const pending = orders.filter(order => order.status === "pending"); const active = orders.filter(order => !["delivered", "canceled"].includes(order.status));
  const metrics = [
    { label: locale === "tr" ? "Bugünkü siparişler" : "Today's orders", value: "38", icon: ShoppingBag, tone: colors.orangeSoft, color: colors.orange },
    { label: locale === "tr" ? "Aktif siparişler" : "Active orders", value: String(active.length), icon: Clock3, tone: colors.blueSoft, color: colors.blue },
    { label: locale === "tr" ? "Teslim edilen" : "Delivered", value: "31", icon: PackageCheck, tone: colors.greenSoft, color: colors.green },
    { label: locale === "tr" ? "Bugünkü satış" : "Today's sales", value: money(1240000, locale), icon: TrendingUp, tone: colors.amberSoft, color: colors.amber },
  ];
  return <AppShell><StateBoundary><PageHeader title={c.dashboard} subtitle={c.greeting} action={!compact && <Button label={c.orders} icon={ShoppingBag} variant="secondary" />} /><Card style={[styles.hero, compact && styles.heroCompact]}><View style={{ flex: 1, minWidth: 0, gap: 5 }}><AppText style={styles.heroKicker} weight="bold">{c.restaurantName}</AppText><AppText style={styles.heroTitle} weight="bold">{accepting ? c.accepting : c.paused}</AppText><AppText style={styles.heroHint}>{accepting ? c.acceptingHint : c.pausedHint}</AppText><View style={styles.live}><Wifi size={14} color={colors.green} /><AppText style={{ color: "#BFC8D7", fontSize: 12 }}>{c.connected}</AppText></View></View><Toggle value={accepting} onChange={setAccepting} label={c.accepting} /></Card><View style={styles.metrics}>{metrics.map(({ label, value, icon: Icon, tone, color }) => <Card key={label} style={[styles.metric, compact && styles.metricCompact]}><View style={[styles.metricIcon, { backgroundColor: tone }]}><Icon size={19} color={color} /></View><AppText style={styles.metricValue} weight="bold">{value}</AppText><AppText style={styles.metricLabel}>{label}</AppText></Card>)}</View><View style={[styles.dashboardGrid, compact && { flexDirection: "column" }]}><Card style={[{ flex: 1.35 }, compact && styles.dashboardPanelCompact]}><View style={styles.cardHeading}><View><AppText weight="bold" style={styles.sectionTitle}>{locale === "tr" ? "Yanıt bekleyenler" : "Waiting for response"}</AppText><AppText style={styles.metricLabel}>{locale === "tr" ? "Süre dolmadan yanıtlayın" : "Respond before the deadline"}</AppText></View><View style={styles.numberBadge}><AppText weight="bold" style={{ color: colors.red }}>{pending.length}</AppText></View></View>{pending.map(order => <View key={order.id} style={styles.waitingRow}><View style={styles.orderMark}><Bell size={18} color={colors.orange} /></View><View style={{ flex: 1 }}><AppText weight="bold">{order.shortCode}</AppText><AppText style={styles.metricLabel}>{order.items.map(item => `${item.quantity}× ${item.name}`).join(", ")}</AppText></View><View style={{ alignItems: "flex-end" }}><AppText weight="bold">{money(order.totalKurus, locale)}</AppText><AppText style={{ color: colors.red, fontSize: 12 }}>{order.deadlineMinutes} min</AppText></View></View>)}</Card><Card style={[{ flex: 1 }, compact && styles.dashboardPanelCompact]}><AppText weight="bold" style={styles.sectionTitle}>{locale === "tr" ? "Operasyon sağlığı" : "Operational health"}</AppText><HealthRow label={c.connected} /><HealthRow label={locale === "tr" ? "Bildirimler bağlı" : "Notifications connected"} /><HealthRow label={locale === "tr" ? "Sipariş kuyruğu güncel" : "Order queue current"} /></Card></View></StateBoundary></AppShell>;
}

function HealthRow({ label }: { label: string }) { return <View style={styles.health}><CheckCircle2 size={18} color={colors.green} /><AppText style={{ flex: 1 }}>{label}</AppText><AppText style={{ color: colors.green, fontSize: 12 }} weight="bold">OK</AppText></View>; }

export function OrdersScreen() { const { locale } = useMock(); const c = getCopy(locale); return <AppShell><StateBoundary><PageHeader title={c.orders} subtitle={locale === "tr" ? "Siparişleri gerçek zamanlı takip edin ve yönetin." : "Track and manage orders in real time."} action={<Button label={c.refresh} variant="secondary" />} /><ResponsiveOrders /></StateBoundary></AppShell>; }

const styles = StyleSheet.create({ hero: { backgroundColor: colors.ink, borderColor: colors.ink, padding: 22, flexDirection: "row", alignItems: "center", gap: 16, marginBottom: 18 }, heroCompact: { alignItems: "flex-start", flexDirection: "column" }, heroKicker: { color: colors.orange, fontSize: 12, letterSpacing: 1 }, heroTitle: { color: colors.white, fontSize: 26 }, heroHint: { color: "#BFC8D7" }, live: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 11 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 13, marginBottom: 18 }, metric: { flex: 1, minWidth: 190, gap: 7 }, metricCompact: { minWidth: 0, flexBasis: "45%", flexGrow: 1 }, metricIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", marginBottom: 5 }, metricValue: { fontSize: 25 }, metricLabel: { color: colors.muted, fontSize: 13 }, dashboardGrid: { flexDirection: "row", gap: 16, alignItems: "flex-start" }, dashboardPanelCompact: { flexGrow: 0, flexShrink: 0, flexBasis: "auto", width: "100%" }, cardHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 10 }, sectionTitle: { fontSize: 18 }, numberBadge: { minWidth: 34, height: 34, borderRadius: 17, backgroundColor: colors.redSoft, alignItems: "center", justifyContent: "center" }, waitingRow: { flexDirection: "row", alignItems: "center", gap: 11, minHeight: 76, borderTopWidth: 1, borderTopColor: colors.line }, orderMark: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.orangeSoft, alignItems: "center", justifyContent: "center" }, health: { minHeight: 55, flexDirection: "row", gap: 10, alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.line },
});
