"use client";
import { getApp, getApps, initializeApp } from "firebase/app";
import { browserSessionPersistence, getAuth, setPersistence } from "firebase/auth";
import { getFunctions } from "firebase/functions";
import {resolveAdminEnvironment} from "./environmentConfig";
const runtime=resolveAdminEnvironment(process.env),config=runtime.firebase;
if(typeof window!=="undefined"&&Object.values(config).some(value=>!value))throw new Error("Missing Firebase public configuration");
const app=getApps().length?getApp():initializeApp(config);
export const auth=getAuth(app);
export const functions=getFunctions(app);
const suffix=runtime.suffix;
export const adminFunctionNames={recordMfa:"recordAdminMfaEnrollment"+suffix,setAccountStatus:"setAdminAccountStatus"+suffix,recoverMfa:"recoverAdminMfa"+suffix} as const;
let persistenceReady:Promise<void>|undefined;
export const ensureSessionPersistence=()=>persistenceReady??=setPersistence(auth,browserSessionPersistence);
