// Test-only Phase 5 adapter. It is not imported by Expo Router or production source.
export const phase5Scenarios = [
  "login", "forgot-password", "invitation", "pending", "suspended", "dashboard", "orders-many",
  "order-detail", "history", "menu-long", "menu-editor", "menu-max-groups", "restaurant-long",
  "reviews", "review-report", "alerts-install", "alerts-denied", "security", "more", "earnings-owner",
  "loading", "empty", "recoverable-error", "offline-empty", "offline-retained", "reconnecting", "stale",
  "permission-denied", "session-expired", "submitting", "validation", "conflict", "unknown-outcome", "dirty-confirmation",
];

const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const copy = locale => locale === "tr" ? {
  skip:"İçeriğe geç", nav:"Ana menü", dashboard:"Ana Sayfa", orders:"Siparişler", history:"Geçmiş", menu:"Menü", restaurant:"Restoran", reviews:"Değerlendirmeler", alerts:"Uyarılar", security:"Güvenlik", more:"Daha Fazla", earnings:"Kazançlar",
  subtitle:"Yerel ve sentetik yeterlilik durumu.", email:"E-posta", password:"Şifre", signIn:"Giriş yap", reset:"Şifreyi yenile", invite:"Daveti kabul et", create:"Yeni hesap", existing:"Mevcut hesap", pending:"Onay bekleniyor", suspended:"Erişim askıya alındı",
  accepting:"Sipariş alınıyor", connected:"Canlı güncellemeler bağlı", pendingOrders:"Bekleyen siparişler", prepare:"Hazırlamaya başla", total:"Toplam", delivered:"Teslim edildi", edit:"Düzenle", save:"Kaydet", cancel:"İptal", anonymous:"Anonim müşteri", report:"Değerlendirmeyi bildir", notification:"Bildirim durumu", enable:"Bildirimleri etkinleştir", install:"Tarayıcı menüsünden Ana Ekrana ekleyin.", account:"Hesap", owner:"Sahip", signOut:"Çıkış yap", estimate:"Hesaplanan tahmin", disclaimer:"Bu değerler ödeme, aktarım, mutabakat, bakiye, fatura, vergi hesabı veya nihai kâr değildir.",
  loading:"Yükleniyor…", empty:"Kayıt yok.", error:"İşlem tamamlanamadı. Tekrar deneyin.", offline:"Çevrimdışı. Yetkili veri kullanılamıyor.", retained:"Çevrimdışı. Önceki yetkili veri gösteriliyor.", reconnecting:"Yeniden bağlanıyor…", stale:"Son yenileme başarısız. Önceki veri güncel olmayabilir.", denied:"Bu sayfaya erişim izniniz yok.", expired:"Oturum sona erdi.", submitting:"Kaydediliyor…", validation:"Alanları kontrol edin.", conflict:"Kayıt başka bir yerde değişti. Güncel durum gösteriliyor.", unknown:"Sonuç doğrulanamadı. Aynı işlem kimliğiyle tekrar deneyin.", dirty:"Kaydedilmemiş değişiklikler silinsin mi?", retry:"Tekrar dene", registrationProof:"Tarayıcı izni tek başına sunucu kaydını kanıtlamaz.", workspace:"Çalışma alanı", status:"Durum", preparing:"Hazırlanıyor", items:"ürün", categories:"Kategoriler", meals:"Yemekler", menuItem:"Menü ürünü", menuDescription:"Duyarlı metin ve düzen yeterliliği için uzun açıklama.", group:"Grup", minimum:"En az", maximum:"En fazla", reason:"Neden", other:"Diğer", internalNote:"İç not", mealFeedback:"Yemek geri bildirimi", published:"Yayınlandı", financialRows:"Finansal satırlar", noCustomer:"Müşteri bilgisi yok.",
} : {
  skip:"Skip to content", nav:"Primary navigation", dashboard:"Dashboard", orders:"Orders", history:"History", menu:"Menu", restaurant:"Restaurant", reviews:"Reviews", alerts:"Alerts", security:"Security", more:"More", earnings:"Earnings",
  subtitle:"Local synthetic qualification state.", email:"Email", password:"Password", signIn:"Sign in", reset:"Reset password", invite:"Accept invitation", create:"New account", existing:"Existing account", pending:"Approval pending", suspended:"Access suspended",
  accepting:"Accepting orders", connected:"Live updates connected", pendingOrders:"Pending orders", prepare:"Start preparing", total:"Total", delivered:"Delivered", edit:"Edit", save:"Save", cancel:"Cancel", anonymous:"Anonymous customer", report:"Report review", notification:"Notification status", enable:"Enable notifications", install:"Install from the browser menu or add to the Home Screen.", account:"Account", owner:"Owner", signOut:"Sign out", estimate:"Calculated estimate", disclaimer:"These values are not payouts, transfers, settlements, balances, invoices, tax calculations, or final profit.",
  loading:"Loading…", empty:"No records.", error:"The operation could not be completed. Try again.", offline:"Offline. Authoritative data is unavailable.", retained:"Offline. Previous authoritative data is shown.", reconnecting:"Reconnecting…", stale:"The latest refresh failed. Previous data may be stale.", denied:"You do not have access to this page.", expired:"Your session has expired.", submitting:"Saving…", validation:"Check the fields.", conflict:"The record changed elsewhere. The current state is shown.", unknown:"The result could not be verified. Retry with the same operation ID.", dirty:"Discard unsaved changes?", retry:"Try again", registrationProof:"Browser permission alone does not prove server registration.", workspace:"Workspace", status:"Status", preparing:"Preparing", items:"items", categories:"Categories", meals:"Meals", menuItem:"Menu item", menuDescription:"Long description for responsive text and layout qualification.", group:"Group", minimum:"Min", maximum:"Max", reason:"Reason", other:"Other", internalNote:"Internal note", mealFeedback:"Meal feedback", published:"Published", financialRows:"Financial rows", noCustomer:"No Customer details.",
};

const button = (label, variant="secondary", attrs="") => `<button type="button" class="ui-button ui-button--${variant}" ${attrs}>${escapeHtml(label)}</button>`;
const field = (label, type="text", value="") => `<label class="ui-field"><span>${escapeHtml(label)}</span><input type="${type}" value="${escapeHtml(value)}"></label>`;
const pageHeader = (title, l) => `<div class="ui-page-header"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(l.subtitle)}</p></div></div>`;
const shell = (l, title, body, active="dashboard") => `<div class="app-shell"><a class="skip-link" href="#main-content">${l.skip}</a><aside class="app-sidebar"><div class="app-brand"><span class="app-brand__mark">H</span><span><strong>Hungrie</strong><small>Restaurant</small></span></div><nav aria-label="${l.nav}"><p class="app-nav__label">${l.workspace}</p>${[["dashboard",l.dashboard],["orders",l.orders],["history",l.history],["menu",l.menu],["restaurant",l.restaurant],["reviews",l.reviews],["settings",l.alerts],["security",l.security],["earnings",l.earnings]].map(([key,label])=>`<a class="app-nav-link" href="#${key}" ${active===key?'data-active="true" aria-current="page"':''}>${label}</a>`).join("")}</nav></aside><div class="app-main"><header class="app-topbar"><div class="app-topbar__identity"><strong>Qualification Restaurant</strong><span class="runtime-status runtime-status--connected">● ${l.connected}</span></div>${button("EN")}</header><main id="main-content" class="app-content" tabindex="-1">${pageHeader(title,l)}${body}</main><nav class="app-bottom-nav" aria-label="Mobile"><a class="app-bottom-link" href="#dashboard">${l.dashboard}</a><a class="app-bottom-link" href="#orders">${l.orders}</a><a class="app-bottom-link" href="#menu">${l.menu}</a><a class="app-bottom-link" href="#more">${l.more}</a></nav></div></div>`;
const auth = (l,title,body) => `<main class="auth-page" tabindex="-1"><header class="auth-topbar"><span class="app-brand"><span class="app-brand__mark">H</span><span><strong>Hungrie</strong><small>Restaurant</small></span></span>${button("EN")}</header><div class="auth-panel"><section class="ui-card auth-form"><h1>${title}</h1>${body}</section></div></main>`;
const orderCards = (l,count=3) => `<div class="order-list">${Array.from({length:count},(_,i)=>`<article class="order-card"><div class="order-card__top"><strong>#Q${String(i+1).padStart(3,"0")}</strong><span class="order-status status-pending">${l.pendingOrders}</span></div><p class="order-card__customer">${2+i} ${l.items}</p><div class="order-card__meta"><span>12:${20+i}</span><strong>₺${25+i}.00</strong></div>${button(l.prepare,"primary")}</article>`).join("")}</div>`;
const dialog = (title,body,l) => `<div class="ui-dialog-backdrop" data-dialog-portal="true"><section class="ui-dialog" role="dialog" aria-modal="true" aria-labelledby="qualification-dialog-title"><h2 id="qualification-dialog-title">${escapeHtml(title)}</h2><div>${body}</div><div class="ui-dialog__actions">${button(l.cancel)}${button(l.save,"primary")}</div></section></div>`;
const stateBody = (l,scenario) => { const key = ({loading:"loading",empty:"empty","recoverable-error":"error","offline-empty":"offline","offline-retained":"retained",reconnecting:"reconnecting",stale:"stale","permission-denied":"denied","session-expired":"expired",submitting:"submitting",validation:"validation",conflict:"conflict","unknown-outcome":"unknown"})[scenario]; const message=l[key]; return `<p class="ui-notice ${["error","validation","denied"].includes(key)?"ui-notice--danger":"ui-notice--warning"}" role="${key==="loading"||key==="reconnecting"?"status":"alert"}">${message}</p><section class="ui-card empty-state"><h2>${message}</h2>${["error","unknown","conflict"].includes(key)?button(l.retry):""}</section>`; };

export function renderPhase5Scenario(scenario, locale="en") {
  const l=copy(locale); let title=l.dashboard, body="", active="dashboard", publicPage=false;
  if(scenario==="login"){publicPage=true;title=l.signIn;body=`<form class="auth-form">${field(l.email,"email","operator@example.invalid")}${field(l.password,"password")}${button(l.signIn,"primary")}</form>`;}
  else if(scenario==="forgot-password"){publicPage=true;title=l.reset;body=`<form class="auth-form">${field(l.email,"email","operator@example.invalid")}${button(l.reset,"primary")}</form>`;}
  else if(scenario==="invitation"){publicPage=true;title=l.invite;body=`<div class="auth-tabs" role="tablist" aria-label="${l.invite}"><button role="tab" aria-selected="true" tabindex="0">${l.create}</button><button role="tab" aria-selected="false" tabindex="-1">${l.existing}</button></div>${field(l.email,"email")}${button(l.invite,"primary")}`;}
  else if(scenario==="pending"||scenario==="suspended"){publicPage=true;title=scenario==="pending"?l.pending:l.suspended;body=`<p>${l.subtitle}</p>${button(l.signOut,"danger")}`;}
  else if(scenario==="dashboard"){body=`<section class="dashboard-hero"><div class="dashboard-hero__icon">H</div><div><p class="eyebrow">${l.restaurant}</p><h2>Qualification Restaurant</h2><p>${l.connected}</p></div><label class="dashboard-acceptance">${l.accepting}<button class="ui-toggle" role="switch" aria-checked="true" aria-label="${l.accepting}"><span></span></button></label></section><section class="dashboard-metrics"><article class="ui-card dashboard-metric"><span>${l.pendingOrders}</span><strong>12</strong></article><article class="ui-card dashboard-metric"><span>${l.orders}</span><strong>48</strong></article></section>`;}
  else if(scenario==="orders-many"){title=l.orders;active="orders";body=`<div class="orders-mobile">${orderCards(l,10)}</div><div class="orders-desktop"><section class="order-board">${["Pending","Preparing","Ready","Delivery"].map((name,i)=>`<section class="order-column"><header><h2>${name}</h2><span>${i+1}</span></header><div class="order-column__list">${orderCards(l,2)}</div></section>`).join("")}</section><aside class="order-detail-panel">${orderCards(l,1)}</aside></div>`;}
  else if(scenario==="order-detail"){title=l.orders;active="orders";body=`<article class="order-detail"><header class="order-detail__header"><h2>#Q001</h2><span class="order-status status-preparing">${l.preparing}</span></header><dl class="order-meta"><div><span>${l.total}</span><strong>₺42.00</strong></div><div><span>${l.status}</span><strong>${l.preparing}</strong></div></dl><section class="order-item-list"><div class="order-line"><span class="order-quantity">2×</span><div><strong>${l.menuItem}</strong><p>${l.menuDescription}</p></div><strong>₺42.00</strong></div></section><div class="order-actions">${button(l.delivered,"primary")}</div></article>`;}
  else if(scenario==="history"){title=l.history;active="history";body=`<div class="history-table ui-card"><table><thead><tr><th>Order</th><th>Status</th><th>${l.total}</th></tr></thead><tbody><tr><td><a href="#detail">#Q001</a></td><td>${l.delivered}</td><td>₺42.00</td></tr></tbody></table></div><div class="history-cards"><article class="ui-card history-card"><a href="#detail">#Q001</a><strong>₺42.00</strong></article></div>`;}
  else if(scenario.startsWith("menu")){title=l.menu;active="menu";const groups=Array.from({length:scenario==="menu-max-groups"?6:1},(_,i)=>`<section class="menu-group"><div class="menu-editor__row">${field(`${l.group} ${i+1}`)}<label>${l.minimum}<input type="number" value="0"></label><label>${l.maximum}<input type="number" value="2"></label></div></section>`).join("");body=`<div class="menu-layout"><aside class="ui-card menu-categories"><h2>${l.categories}</h2>${button(l.meals)}</aside><section class="menu-workspace"><div class="menu-items"><article class="ui-card menu-item"><div class="menu-item__media" role="img" aria-label="${l.menuItem}">□</div><div class="menu-item__body"><h3>${l.menuItem}</h3><p>${l.menuDescription}</p><strong>₺42.00</strong></div><div class="menu-item__actions">${button(l.edit)}</div></article></div></section></div>`;if(scenario!=="menu-long")body+=dialog(l.edit,`<div class="menu-editor">${field(l.menuItem,"text",l.menuItem)}${groups}</div>`,l);}
  else if(scenario==="restaurant-long"){title=l.restaurant;active="restaurant";body=`<section class="restaurant-cover ui-card"><div><h2>Qualification Restaurant With An Intentionally Long Localized Name</h2><span>active</span></div></section><div class="restaurant-grid"><section class="ui-card restaurant-form"><h2>${l.restaurant}</h2><div class="form-grid">${field("Name","text","Qualification Restaurant")}${field("Address","text","A very long address for wrapping and text scaling")}${field("Minimum order","text","25.00")}</div></section></div>`;}
  else if(scenario==="reviews"||scenario==="review-report"){title=l.reviews;active="reviews";body=`<p class="privacy-note">${l.anonymous}</p><div class="review-tabs" role="tablist" aria-label="${l.reviews}"><button role="tab" aria-selected="true" tabindex="0">${l.reviews}</button><button role="tab" aria-selected="false" tabindex="-1">${l.mealFeedback}</button></div><div class="review-list"><article class="ui-card review-card"><div class="review-card-head"><strong>${l.anonymous}</strong><span class="ui-status ui-status--success">${l.published}</span></div><blockquote class="review-comment">${l.subtitle}</blockquote>${button(l.report)}</article></div>`;if(scenario==="review-report")body+=dialog(l.report,`<label class="ui-field"><span>${l.reason}</span><select><option>${l.other}</option></select></label><label class="ui-field"><span>${l.internalNote}</span><textarea aria-describedby="note-help"></textarea><small id="note-help">0/500</small></label>`,l);}
  else if(scenario.startsWith("alerts")){title=l.alerts;active="settings";body=`<div class="alerts-page"><section class="ui-card alerts-status"><span class="alerts-icon" aria-hidden="true">!</span><div><h2>${l.notification}</h2><p>${scenario==="alerts-denied"?l.denied:l.install}</p><small>${l.registrationProof}</small></div></section><section class="ui-card alerts-actions">${button(l.enable,"primary")}</section></div>`;}
  else if(scenario==="security"){title=l.security;active="security";body=`<div class="security-page"><section class="ui-card security-account"><div><h2>${l.account}</h2><dl><div><dt>${l.email}</dt><dd>operator@example.invalid</dd></div><div><dt>Role</dt><dd>${l.owner}</dd></div></dl></div></section><div class="security-grid"><section class="ui-card security-action"><h2>${l.reset}</h2>${button(l.reset)}</section><section class="ui-card security-action"><h2>${l.signOut}</h2>${button(l.signOut,"danger")}</section></div></div>`;}
  else if(scenario==="more"){title=l.more;active="more";body=`<div class="more-page"><section class="ui-card more-list">${[l.history,l.restaurant,l.reviews,l.alerts,l.security,l.earnings].map(label=>`<a class="more-row" href="#"><span aria-hidden="true">•</span><span><strong>${label}</strong></span><span aria-hidden="true">›</span></a>`).join("")}</section></div>`;}
  else if(scenario==="earnings-owner"){title=l.earnings;active="earnings";body=`<div class="earnings-page"><aside class="earnings-disclaimer"><strong>${l.estimate}</strong><p>${l.disclaimer}</p></aside><section class="earnings-metrics"><article class="earnings-metric"><span>${l.estimate}</span><strong>₺100.00</strong></article><article class="earnings-metric"><span>${l.delivered}</span><strong>4</strong></article></section><section class="earnings-card"><h2>${l.financialRows}</h2><p>${l.noCustomer}</p></section></div>`;}
  else if(scenario==="dirty-confirmation"){title=l.menu;active="menu";body=`<section class="ui-card"><h2>${l.menu}</h2></section>${dialog(l.dirty,"<p>Unsaved changes will be lost.</p>",l)}`;}
  else { title=scenario==="permission-denied"?l.earnings:l.dashboard; body=stateBody(l,scenario); }
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${escapeHtml(title)} · Hungrie Restaurant</title><link rel="stylesheet" href="/phase5-assets/tokens.css"><link rel="stylesheet" href="/phase5-assets/typography.css"><link rel="stylesheet" href="/phase5-assets/components.css"><link rel="stylesheet" href="/phase5-assets/responsive.css"></head><body><div id="root">${publicPage?auth(l,title,body):shell(l,title,body,active)}</div><script>${qualificationInteractions}</script></body></html>`;
}

const qualificationInteractions = `(()=>{const tabs=[...document.querySelectorAll('[role="tab"]')];for(const tab of tabs){tab.addEventListener('click',()=>{for(const other of tabs){const selected=other===tab;other.setAttribute('aria-selected',String(selected));other.tabIndex=selected?0:-1;}});}document.querySelector('[role="tablist"]')?.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const current=tabs.indexOf(document.activeElement),next=event.key==='Home'?0:event.key==='End'?tabs.length-1:event.key==='ArrowRight'?(current+1)%tabs.length:(current-1+tabs.length)%tabs.length;event.preventDefault();tabs[next]?.focus();tabs[next]?.click();});const dialog=document.querySelector('[role="dialog"]');if(dialog){const portal=dialog.parentElement;if(portal&&portal.parentElement!==document.body)document.body.appendChild(portal);const background=[...document.body.children].filter(node=>node.id==='root');background.forEach(node=>{node.inert=true;node.setAttribute('aria-hidden','true');});const focusable=[...dialog.querySelectorAll('button,input,select,textarea,[href]')];focusable[0]?.focus();document.addEventListener('keydown',event=>{if(event.key==='Escape'){background.forEach(node=>{node.inert=false;node.removeAttribute('aria-hidden');});dialog.parentElement?.remove();document.querySelector('main')?.focus();}if(event.key==='Tab'&&focusable.length){const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});}})()`;
